{
 "title": "Hookshot",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "interval", "label": "Interval", "query": "1m,5m,10m,30m,1h,6h,12h,1d" },
   { "name": "delta", "label": "2x Interval", "query": "2m,10m,20m,1h,2h,12h,1d,2d" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_heap_bytes", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hookshot_connections", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Connection Events Failed",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "idelta(hookshot_connection_event_failed[$__interval])",
     "legendFormat": "{{ event }}"
    }
   ]
  },
  {
   "title": "Notifications Service Up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hookshot_notifications_service_up",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Notifications Watchers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hookshot_notifications_watchers",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  { "title": "Queue Event Pushes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Queue Event Pushes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "idelta(hookshot_queue_event_pushes[$__interval])",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "Matrix Event Pushes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "idelta(hookshot_queue_event_pushes{event=~\".*matrix.*\"}[$__interval])",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "Notifications Event Pushes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "idelta(hookshot_queue_event_pushes{event=~\"notifications.*\"}[$__interval])",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "GitHub Event Pushes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "idelta(hookshot_queue_event_pushes{event=~\"github.*\"}[$__interval])",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "GitLab Event Pushes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "idelta(hookshot_queue_event_pushes{event=~\"gitlab.*\"}[$__interval])",
     "legendFormat": "idelta(metric)"
    },
    {
     "expr": "idelta(hookshot_queue_event_pushes{event=~\"gitlab.*\"}[$__interval])",
     "legendFormat": "metric"
    }
   ]
  },
  {
   "title": "Generic Event Pushes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "idelta(hookshot_queue_event_pushes{event=~\"generic-webhook.*\"}[$__interval])",
     "legendFormat": "{{event}}"
    },
    {
     "expr": "idelta(hookshot_queue_event_pushes{event=~\"response.generic-webhook.*\"}[$__interval])",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "Jira Event Pushes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "idelta(hookshot_queue_event_pushes{event=~\"jira.*\"}[$__interval])",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "Figma Event Pushes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "idelta(hookshot_queue_event_pushes{event=~\"figma.*\"}[$__interval])",
     "legendFormat": "{{event}}"
    }
   ]
  },
  { "title": "Feeds", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Feed Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "targets": [
    { "expr": "hookshot_feeds_count", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Feed Fetch Time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "hookshot_feeds_fetch_ms", "legendFormat": "{{__name__}}" }
   ]
  },
  { "title": "HTTP Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Webhooks HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "idelta(hookshot_webhooks_http_request[$__interval])",
     "legendFormat": "{{method}} - {{path}}"
    }
   ]
  },
  {
   "title": "Provisioning HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "idelta(hookshot_provisioning_http_request[$__interval])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  { "title": "Matrix API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Matrix API Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "idelta(matrix_api_calls[$__interval])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Matrix API Calls Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "idelta(matrix_api_calls_failed[$__interval])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Matrix Appservice Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "idelta(matrix_appservice_events[$__interval])",
     "legendFormat": "matrix_appservice_events"
    }
   ]
  }
 ]
}