name: matrix-hookshot-dev

services:
  valkey:
    image: valkey/valkey:9

  # element:
  #   image: vectorim/element-web:develop
  #   volumes:
  #     - ./contrib/docker/element/config.json:/app/config.json:ro
  #   ports:
  #     - "127.0.0.1:8083:80"

  init-app:
    image: alpine:3
    command: sh -c 'if [ ! -f /hookshot-data/passkey.pem ]; then echo "Generating new passkey"; apk add openssl; openssl genpkey -out /hookshot-data/passkey.pem -outform PEM -algorithm RSA -pkeyopt rsa_keygen_bits:4096; fi'
    volumes:
      - hookshot-data:/hookshot-data

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "9001:9001"
      - "9002:9002"
      - "9993:9993"
    volumes:
      - hookshot-data:/data
      - ./contrib/docker/:/contrib:ro
      # Map your local files into the container's /data folder:
      # - ./config.yml:/data/config.yml:ro
      - ./registration.railway.production.yml:/data/registration.railway.production.yml:ro
      - ./config.railway.production.yml:/data/config.railway.production.yml:ro
      # - ./registration.yml:/data/registration.yml:ro
      - ./passkey.pem:/data/passkey.pem:ro
      - ./github-key.pem:/data/github-key.pem:ro
    links:
      - valkey
    command: node /usr/bin/matrix-hookshot/App/BridgeApp.js /data/config.railway.production.yml /data/registration.railway.production.yml
    depends_on:
      valkey:
        condition: service_started
      init-app:
        condition: service_completed_successfully
    develop:
      watch:
        - action: rebuild
          path: .
          ignore:
            - node_modules/
            - docs/
            - public/
            - book/
            - .*/

volumes:
  hookshot-data: